# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TSWoW 0.12 ARCHIVE
email:
description: >- # this means to ignore newlines until "baseurl:"
  TSWoW is a modding framework for World of Warcraft: Wrath of the Lich King.
  This wiki contains everything you need to get started modding the game with
  our tool.

minimal_mistakes_skin: default
search: true

after_footer_scripts:
  - /assets/js/contribute.js

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "TSWoW 0.12 Archive"
  avatar : "/assets/images/bio-photo.png"
  bio    : "WoW Modding Unleashed"
  links:
    - label: "Wiki"
      icon: "fas fa-fw fa-link"
      url: "https://github.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tswow/tswow"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/M89n6TZh9x"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  # _documentation
  - scope:
      path: ""
      type: documentation
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      toc: true

  # _introduction
  - scope:
      path: ""
      type: introduction
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false
      toc: true
      sidebar:
        nav: "introduction"

  # _examples
  - scope:
      path: ""
      type: examples
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      toc: true

collections:
  documentation:
    output: true
    permalink: /:collection/:path/

  introduction:
    output: true
    permalink: /:collection/:path/

  examples:
    output: true
    permalink: /:collection/:path/

  # hack to display homepage on github pages
  home:
    output: true
    permalink: /:collection/:path/
